### ISSUE TITLE
How about overlapping pooling

### ISSUE THREAD

**Issue by Chokurei** [heuritech/convnets-keras#10]
Thank you for your kind upload
I tried your Alexnet, it seems nice

But how about the Overlapping pooling
In your code, maxpooling stride is (3, 3), I think is (2, 3) or something
Hope your reply 

thank you a lot

**Comment by Chokurei** [comment]
I misunderstand what you mean just now, thank you so much
MaxPooling2D((3, 3), strides=(2,2))

**Comment by leonardblier** [comment]
Hi, thank you for your question.

Indeed, there is overlapping in some MaxPooling layers. These aren't choices I have made myself, it is the setting of the original paper.
There is a section in the paper about this overlapping choice (Section 3.4), maybe you will find more informations there : https://papers.nips.cc/paper/4824-imagenet-classification-with-deep-convolutional-neural-networks.pdf

**Comment by Chokurei** [comment]
Thank you for the reply, I understand it now

**Comment by leonardblier** [comment]
You are welcome, I close the issue.
