### ISSUE TITLE
Documentation bug in README.md

### ISSUE THREAD

**Issue by ekolve** [heuritech/convnets-keras#3]
In the section 'How to use convnets', the first example explains how to use alexnet and the second example looks like it is supposed to explain how to use VGG, but duplicates the alexnet example with the exception of changing the color mode to bgr.  I would expect the second example to specify 'vgg16' and load the vgg weights.

**Comment by leonardblier** [comment]
Thank you, I have just modified it, and add a 'commented) line for the VGG19 network
