### ISSUE TITLE
Are you interested in doubling the heatmap resolution? (4x more pixels)

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [heuritech/convnets-keras#37]
Hi, i'm fairly new in github so it's the only place I found to ask this. 
While I was working on a kaggle competition, I had to detect fishes in a image.
This lead me to try to increase the resultion of the heatmaps from this repository.
I managed to do it by changing the last pooling layer (stride of (1,1) instead of (2,2)) and also the next convolution layer accordingly. (I add zeros and doubled the size of the convolution to match the original architecture, as if it was a sliding window).
I works pretty well right now. 
I was wondering if you were interested by this code if I were to take the time to make a proper pull request.
Thank you very much.

**Comment by walterreade** [comment]
@gabrieldemarmiesse - I'd like to see it, it it's not too much trouble.

**Comment by gabrieldemarmiesse** [comment]
Since I didn't get any answers for a while, I made a repository with some code that does it: 
https://github.com/gabrieldemarmiesse/heatmaps

It performs the increase of heatmap resolution automatically, so no need to specify anything.

I'll make a pull request on this repository if someone from the heuritech team asks me to, because I'm busy this week and I'm not sure if my pull request is going to be reviewed. If you have any questions, feel free to ask. Don't hesitate to contribute too!
