### ISSUE TITLE
Comment bug in convnets.py cars vs dogs

### ISSUE THREAD

**Issue by ekolve** [heuritech/convnets-keras#4]
In the __main__ section of convnets.py, there is the following:

    ### Here is a script to compute the heatmap of the cars synsets.
    ## We find the synsets corresponding to cars on ImageNet website
    s = "n02084071"

synset_id n02084071 refers to dogs (http://wordsrus.info/synsets/n02084071.html) not cars.

**Comment by EloiZ** [comment]
Thanks a lot, it has been corrected
